Page({
  data: {
    baseList: [
      {
        title: '基础',
        subhead: '包含颜色、文本、图标',
        id: '1',
        imgUrl: '/assets/ComUI/base/jichu.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '视图',
        subhead: '包含通告栏、标签、徽章等',
        id: '2',
        imgUrl: '/assets/ComUI/base/shitu.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '操作反馈',
        subhead: '包含对话框、进度条、动作面板等',
        id: '3',
        imgUrl: '/assets/ComUI/base/caozuo.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '表单',
        subhead: '包含输入框、单选框、复选框等',
        id: '4',
        imgUrl: '/assets/ComUI/base/biaodan.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '布局',
        subhead: '包含列表、浮层、卡片等',
        id: '5',
        imgUrl: '/assets/ComUI/base/buju.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '导航',
        subhead: '包含标签栏、导航栏、分段器等',
        id: '6',
        imgUrl: '/assets/ComUI/base/daohang.png',
        visibleImg: true,
        pageUrl: '/subpackages/navigationPage/pages/index/index',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
      {
        title: '高阶组件',
        subhead: '包含日历等',
        id: '7',
        imgUrl: '/assets/ComUI/base/query.png',
        visibleImg: true,
        pageUrl: '/subpackages/module/pages/base/base',
        iconUrl: '/assets/ComUI/base/right-circle.png',
      },
    ],
  },
  onLoad: function () {},
})
